export const HOME_PAGE = 'Today'
export const INBOX_PAGE = 'Inbox'
export const CALENDAR_PAGE = 'Calendar'
export const TRANSACTIONS_PAGE = 'Transaction history'
export const PERKS_PAGE = 'Perks'
export const PINK_COLOR = '#CE1449'
